source 'https://rubygems.org'

gem 'allure-cucumber', '~> 2.13.6'
gem 'appium_lib'
gem 'builder'
gem 'capybara', '~> 3.33'
gem 'cucumber', '~> 4.1'
gem 'magic_encoding'
gem 'minitest', '~> 5.14', '>= 5.14.2'
gem 'parallel_tests'
gem 'pry'
gem 'reportportal'
gem 'rspec', '~> 3.8'
gem 'selenium-webdriver', '~> 3.142'
gem 'test-unit'
gem 'test-unit-runner-junitxml'
gem 'webdrivers', '~> 4.4'
gem 'minitest', '~> 5.14', '>= 5.14.2'
